# Generated by Django 2.2.6 on 2019-11-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='last_payment',
        ),
        migrations.AddField(
            model_name='subscription',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.Payment'),
        ),
    ]
