# Generated by Django 2.2.6 on 2019-11-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20191109_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payments',
        ),
        migrations.AddField(
            model_name='payment',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.Subscription'),
        ),
    ]
