# Generated by Django 3.0.2 on 2020-01-25 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import relativefilepathfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('template_file', relativefilepathfield.fields.RelativeFilePathField(match='ad_template_*', path='C:\\Users\\Kingo\\Documents\\Coding 2019\\Purple-Pages\\adverts\\templates')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('strapline', models.CharField(blank=True, max_length=100)),
                ('text_content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', upload_to='adverts/', width_field='image_width')),
                ('image_height', models.IntegerField(default=0)),
                ('image_width', models.IntegerField(default=0)),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=30)),
                ('background_color_class', models.CharField(default='white', max_length=15)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('view_counter', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('boards', models.ManyToManyField(to='boards.Board')),
                ('ppuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='adverts.AdvertTemplate')),
            ],
        ),
    ]
