# Generated by Django 3.0.2 on 2020-01-25 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='background_color_class',
            field=models.CharField(default='white', max_length=15),
        ),
        migrations.AddField(
            model_name='advert',
            name='boards',
            field=models.ManyToManyField(to='boards.Board'),
        ),
        migrations.AddField(
            model_name='advert',
            name='ppuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
