# Generated by Django 2.2.6 on 2019-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='textContent',
            field=models.TextField(default=''),
        ),
    ]
