# Generated by Django 3.0.2 on 2020-04-03 09:21

import adverts.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='active',
        ),
        migrations.AddField(
            model_name='advert',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to=adverts.models.Advert.image_upload_path, width_field='image_width'),
        ),
    ]
