# Generated by Django 2.2.6 on 2019-10-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('adverts', '0002_advert_textcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='on_boards',
            field=models.ManyToManyField(to='boards.Board'),
        ),
    ]
