# Generated by Django 3.0 on 2019-12-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_advert_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverttemplate',
            name='template_file',
            field=models.FilePathField(match='ad_template_*', path='C:\\Users\\Kingo\\Documents\\Coding 2019\\Purple-Pages\\adverts\\templates'),
        ),
    ]
