# Generated by Django 3.0 on 2019-12-05 15:11

from django.db import migrations
import relativefilepathfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_auto_20191205_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverttemplate',
            name='template_file',
            field=relativefilepathfield.fields.RelativeFilePathField(match='ad_template_*', path='C:\\Users\\Kingo\\Documents\\Coding 2019\\Purple-Pages\\adverts\\templates'),
        ),
    ]
