# Generated by Django 3.0 on 2019-12-10 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_auto_20191205_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/adverts/'),
        ),
        migrations.AddField(
            model_name='advert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='strapline',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='advert',
            name='textContent',
            field=models.TextField(blank=True),
        ),
    ]
