# Generated by Django 3.0 on 2019-12-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_auto_20191210_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='link_text',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
