# Generated by Django 2.2.6 on 2019-11-10 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCodeDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dateActive', models.DateField(auto_now_add=True)),
                ('postCodeDistrict', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='boards.PostCodeDistrict')),
            ],
        ),
    ]
