# Generated by Django 2.2.6 on 2019-10-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postCodeDistrict', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=30)),
                ('dateActive', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
