# Generated by Django 2.2.6 on 2019-11-08 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCodeDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='postCodeDistrict',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='boards.PostCodeDistrict'),
        ),
    ]
